### ISSUE TITLE
Do I even need those yet? quest imposiible

### ISSUE THREAD

**Issue by Scienceboy999** [MasterEnderman/Divine-Equilibrium#64] opened 2021-01-15 22:54 UTC
There is no possible recipe to make terra ingot's in the Gaia stage since growth powder can only be made in the void stage.

**Comment by MasterEnderman** [comment] 2022-04-14 12:28
Duplicate of: https://github.com/MasterEnderman/Divine-Equilibrium/issues/60

**Closed by MasterEnderman** 2022-04-14 12:28 UTC
Labels: bug, duplicate
