### ISSUE TITLE
Crushing Block recipe to get soul seems to be broken

### ISSUE THREAD

**Issue by Toksyuryel** [MasterEnderman/Divine-Equilibrium#56] opened 2020-08-10 17:02 UTC
I tossed my head down and dropped the crushing block down onto it, and it just shoots out the side instead of being turned into a soul. As a soul is required for the ring of gaia, this is progression-blocking me.

**Comment by MasterEnderman** [comment] 2020-08-11 13:34
I can't reproduce this behaviour on my and could you try to use the repair function of the twitch launcher and see if this bug still occurs?

**Comment by Toksyuryel** [comment] 2020-08-11 14:43
I don't use the Twitch launcher because it doesn't support my OS, I use MultiMC on Linux.

**Comment by MasterEnderman** [comment] 2020-08-11 19:23
Well sorry for assuming that you're using the twitch app in the first place. The thing is I already got a few reports where something didn't function correctly because the twitch app didn't properly install the pack. Actually I'm using MultiMC to play the pack as well.
The problem is I just started the pack up dropped a head on the floor let a crushing block fall on it and it converted into the soul item.

**Comment by Dr-Game** [comment] 2020-08-17 14:01
Make sure that you're using a Player Head and not a [Player's Username]'s Head. The Crushing Block will only crush standard Player Heads into souls, and you can craft Player Heads with a ritual. It will not accept a head that you got from dying, though that should probably be fixed with an NBT thing or something.

**Comment by MasterEnderman** [comment] 2020-08-17 15:03
It should ignore nbt data. So every type of player head should work. At least that's how it works in my instance of the pack.

**Comment by DemonLotusYT** [comment] 2020-08-19 10:24
Soul recipe with my skull doesnt work even with a profile repair

**Comment by z-Tau** [comment] 2020-08-25 04:59
Just wanted to add I was having the same issue as well, I had to create a head using the ritual.

**Comment by Ricviu** [comment] 2020-08-25 07:14
Can confirm, using the player head obtained in death does not work, but a 'vanilla' head done through the ritual works

**Closed** 2022-04-14 14:34 UTC
Labels: bug, fixed in dev
