### ISSUE TITLE
Normal Bone Gear not possible to craft in Insomnia Stage

### ISSUE THREAD

**Issue by Andstar** [MasterEnderman/Divine-Equilibrium#66] opened 2021-08-01 16:23 UTC
I need to craft the Gear to complete the Automatic Constructor Quest in Insomnia Stage because Crystal Quartz is not obtainable in the Void Dimension (at least not to my knowledge).
I have unlocked all Game Stages that are possible at that point.

**Comment by MasterEnderman** [comment] 2022-04-11 21:43
Duplicate of: https://github.com/MasterEnderman/Divine-Equilibrium/issues/54

**Closed by MasterEnderman** 2022-04-11 21:43 UTC
Labels: duplicate
